name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-deploy-docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    defaults:
      run:
        working-directory: wiki

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Check formatting
        run: npx prettier@3 --check .

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env

      - name: Get Version
        id: version
        uses: ./.github/actions/obtain-version

      - name: Build and Deploy Documentation
        uses: ./.github/actions/build-docs
